### ISSUE TITLE
Crash on android : Receiver not registered 

### ISSUE THREAD

**Issue by farhan-spinny** [hirbod/react-native-volume-manager#9]
On firebase I am getting this error for some devices.
Implementation is working for almost all other users.

VolumeManagerModule.unregisterVolumeReceiver
```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.my.package/com.my.package.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.reactnativevolumemanager.VolumeManagerModule$b@8a8518c
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5396)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5347)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5294)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:53)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

```
useEffect(() => {
  const volumeListener = VolumeManager.addVolumeListener((result) => {
    console.log(result.volume);
  });

  return function () {
    volumeListener.remove();
  }
}, []);
```

Any suggestions?

**Comment by hirbod** [comment]
I have a fix for this ready in the upcoming version

**Comment by hirbod** [comment]
Version 1.3.0 has been released. This issue is resolved now. Thanks for reporting!
